image: node:6

stages:
  - build

variables:
  DOCKER_DRIVER: overlay

before_script:
  - REF_NAME=$(echo $CI_COMMIT_REF_NAME | tr '/' '_')

build-dest:
  stage: build
  script:
    - ./run-build.sh package
  tags:
    - dind
  # Cache downloaded dependencies and plugins between builds.
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - node_modules/
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}_${CI_PIPELINE_ID}"
    paths:
      - dest/
    expire_in: 5 days
