version: '3.1'

services:
  node:
    build: 
      context: .
      args:
        - NODE_ENV=development
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development
